name: intercode
dependencies:
  - python=3.9
  - pip
  - pip:
    - ansiconv
    - config
    - cryptography
    - docker
    - gnureadline
    - gymnasium
    - mysql-connector-python
    - nltk
    - openai
    - pandas
    - pymysql
    - pytest
    - rich
    - rpyc
    - scikit-learn
    - sqlalchemy
    - tenacity
    - sqlite3-to-mysql
    - google-generativeai